### ISSUE TITLE
AirPods (3rd generation)

### ISSUE THREAD

**Issue by Keeo** [adolfintel/OpenPods#140]
Hi, would it be possible to add support for 3rd generation of airpods?
https://www.apple.com/airpods-3rd-generation/

**Comment by jvllmr** [comment]
My 3rd gen air pods are mistaken as Powerbeats 3. I would like to give it a shot with fixing this sometime soon but I don't own Powerbeats 3 to verify the other direction :(

**Comment by d4rken** [comment]
This is due to only comparing part of and not the full identifier. There is overlap:

* PowerBeats 3 have [0x0320](https://github.com/d4rken-org/capod/blob/aef14a9cd2aecf799c680f0ac5eb1fb5b5a205a8/app/src/main/java/eu/darken/capod/pods/core/apple/beats/PowerBeats3.kt#L55)

* AirPods Gen3 have [0x1320](https://github.com/d4rken-org/capod/blob/aef14a9cd2aecf799c680f0ac5eb1fb5b5a205a8/app/src/main/java/eu/darken/capod/pods/core/apple/airpods/AirPodsGen3.kt#L65)


currently it's just one character of the identifier:

https://github.com/adolfintel/OpenPods/blob/104dc3454b249f7861d3aefaf7652e4a3b5796f4/app/src/main/java/com/dosse/airpods/pods/PodsStatus.java#L71-L94

**Comment by d4rken** [comment]
#147 should fix this, please test it when you have time.
