### ISSUE TITLE
Allow users to reject permissions

### ISSUE THREAD

**Issue by MasonProtter** [adolfintel/OpenPods#178]
It feels very user-hostile and shady that this app refuses to work unless it is granted so many unnecessary permissions. Is there any reason it can't just disable features that require things like background precise location permissions if the user doesn't want to enable them?

**Comment by Electric1447** [comment]
Those features are required for the app to function.
The location permission is an issue from google on BLE permissions.

Due to the nature of the app being open source you can review the code yourself and see that no personal data (or any data except the app settings) or collected or stored .

Also this app has no internet permission and thus cannot connect to the internet.
