### ISSUE TITLE
Notification should report most recent battery life report for case and in-case Airpods

### ISSUE THREAD

**Issue by taylorkline** [adolfintel/OpenPods#55]
First off, great thanks for the app. Appreciate that it's FOSS and on F-Droid.

The battery life for the case and any Airpods left in the case is reported only briefly, and then only the in-ear Airpods continue to report battery life. The notification should ideally continue displaying the most recently seen battery life reports for the case + Airpods while there is still at least one Airpod connected.

In case it's useful to know, I am using Airpods Pros.

**Comment by adolfintel** [comment]
It can be done but it won't be very reliable. The airpods only transmit the status of the case when at least one of them is charging. While we could simply store the last known status of the case, that wouldn't work if you have 2 or more sets of airpods, because there's no reliable way to distinguish them.
